require("plugin/packer_nvim")
require("plugin/catppuccin")
require("plugin/nvim_tree")
require("plugin/treesitter")
require("plugin/comment")
require("plugin/autopairs")
require("plugin/visual_multi")
require("plugin/bufferline")
require("plugin/lsnip")
require("plugin/nvim_cmp")
require("plugin/bufdelete")
require("plugin/lsp")
require("plugin/colorize")

